name: Compare Function Validation
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake -B build
          cmake --build build
          cd build && ctest --output-on-failure 